### ISSUE TITLE
10、创建 .gitlab-ci.yml 文件

### ISSUE THREAD

**Issue by bingoran** [bingoran/Blog#10]
.gitlab-ci.yml 是 CI/CD 的核心文件，gitlab 根据配置进行项目的 CI/CD 流程，**这个文件是放在项目根目录的**；

这里使用的是 yaml 配置语言，不熟悉语法的自己谷歌

### 变量定义

变量的作用是将不希望暴露的敏感信息配置在 gitlab 里边；

这样，虽然我们能看到配置文件，像私钥，IP 这样的访问这是不能直接读取到的；

定义完的变量在  .gitlab-ci.yml 文件里边可以通过下面的形式访问

```yaml
${SERVER_ADDR}
```

![image-20210419160339617](http://lstatic.bingoran.com/common/img/image-20210419160339617.png)

### .gitlab-ci.yml

注意：这里的 ssh 文件传输需要先在指定服务器配置免密传输，配置方式我写在了 “在 gitlab CICD 上使用SSH密钥” 这篇里边

```yaml
#====================常量声明==============================
# gitlab常量说明（从 gitlab 变量读取）
# SSH_PRIVATE_KEY 私钥
# SERVER_ADDR 目标服务器地址
# 本地常量声明
variables:
  # 远程服务器部署目录
  DEPLOY_SERVER_PATH_PRO: /home/app/web/demo #正式环境
  DEPLOY_SERVER_PATH_DEV: /home/app/web/demo #测试环境

#====================缓存==============================
cache: # 缓存目录
  paths:
    - node_modules # 会监听 package.json 文件的变化更新
    - dist # 打包完成后代码存放的地方

#====================公共配置==============================
.common-config: &commonConfig
  image: node:14.15.4 # 指定 node 版本
  only: # 表示仅在仓库的哪些分支上执行构建
    refs:
      # 正式环境
      - master
      - release
      - production
      - pro
      # 预发布环境 | 暂时没有配置需要手动操作
      # - pre
      # 测试环境
      - develop
      - dev
      - test   

.common-npm: &commonNpm
  before_script:
    # 定义变量 如NODE环境变量
    - echo "node 环境判断"; 
    - NODE_ENV=`if [[ ${CI_COMMIT_REF_NAME:0:3} = "dev" || ${CI_COMMIT_REF_NAME:0:4} = "test" ]]; 
               then 
                 echo "dev"; 
               else 
                 echo "pro"; 
               fi`;
    - echo "当前 node 环境 ${NODE_ENV}";
    # 安装 cnpm 加速打包过程
    - npm install cnpm -g --registry=https://registry.npm.taobao.org

.common-deploy: &commonDeploy
   before_script:
    # 定义变量 DEPLOY_SERVER_PATH
    - DEPLOY_SERVER_PATH=`if [[ ${CI_COMMIT_REF_NAME:0:3} = "dev" || ${CI_COMMIT_REF_NAME:0:4} = "test" ]]; 
                            then 
                              echo "${DEPLOY_SERVER_PATH_DEV}"; 
                            else 
                              echo "${DEPLOY_SERVER_PATH_PRO}";
                            fi`;
    - echo "服务器工作目录： ${DEPLOY_SERVER_PATH}";
    # 加载私钥
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
 
#====================部署阶段==============================
stages: # 部署阶段
  - install # 安装依赖
  - build # 打包编译
  - deploy # 部署到目标服务器

# 阶段1：安装依赖
install-job:
  tags:
    - test
  stage: install
  <<: *commonConfig
  <<: *commonNpm
  script:
    - cnpm install

# 阶段2: 构建项目
build-job:
  tags:
    - test
  stage: build
  <<: *commonConfig
  <<: *commonNpm
  script:
    - echo "开始构建";
    - if [ $NODE_ENV = "dev" ];
      then
        echo "测试环境开始构建：命令 cnpm run beta";
        cnpm run beta;
      else
        echo "正式环境开始构建：命令 cnpm run build2";
        cnpm run build2;
      fi;

# 阶段3：部署结果到目标服务器
deploy-job: 
  tags:
    - test
  stage: deploy
  <<: *commonConfig
  <<: *commonDeploy
  script:
    # 远程部署目录备份并部署新文件
    - pwd #  输出下当前 gitlab 工作目录路径
    - echo "服务器地址： ${SERVER_ADDR}";
    - echo "服务器工作目录： ${DEPLOY_SERVER_PATH}";
    - ssh root@${SERVER_ADDR} 'bash -s' < `pwd`/backup.sh ${DEPLOY_SERVER_PATH}
    - scp -r ./dist/* root@${SERVER_ADDR}:${DEPLOY_SERVER_PATH}  # 将打包好的文件上到发布项目的服务器中的，放到nginx能访问到的文件夹下
```

backup.sh

```sh
#!/bin/bash
echo "远程服务器登录成功"
cd $1 # $1 是部署服务器的名称
FILE_NAME=`mktemp -u pm.dev.XXXXX` # 创建临时文件
DATE=`date +"%Y-%m-%d_%H%M"`
BACKUP="backup"
tar -zcvf ${FILE_NAME}.${DATE}.tar.gz ./* --exclude="$BACKUP"
# 移动备份文件到备份文件夹
if [ ! -d "$BACKUP" ]; then
mkdir "$BACKUP"
fi
mv ${FILE_NAME}.${DATE}.tar.gz "$BACKUP"
# 删除远程服务器部署目录中除backup外所有文件
ls|egrep -v "$BACKUP"|xargs rm -rf
echo "远程脚本执行完成，执行目录：`pwd` 备份文件夹：`ls`"
```

### 运行命令，重启动
