### ISSUE TITLE
11、在 gitlab 为 CICD 配置 ssh 密钥登录

### ISSUE THREAD

**Issue by bingoran** [bingoran/Blog#11]
### 原理

A 机器免密登录 B 机器，A机器IP（192.168.1.210），B机器IP（192.168.1.211），正确姿势：

1、在A机器上生成密码：

```bash
$ cd ~/.ssh
$ ssh-keygen -t rsa -C 'XXX@XXX.com'
```

密钥名字可以自己随便取，默认是 id_rsa，如果使用默认名字，一路回车即可。

2、把A机器生成的公钥 id_rsa.pub 文件发送到 B 机器上：

```bash
$ ssh-copy-id -i /root/.ssh/id_rsa.pub root@192.168.1.211
```

系统自动在B机器 root/.ssh 目录中生成 authorized_keys 文件

3、在 A 机器上测试SSH登录 B 机器免密：

```bash
$ ssh 192.168.1.211
```

### 1、在阿里云服务器根目录生成公钥私钥

```bash
ssh-keygen -t rsa -C 'bingoranlb@gmail.com'
```

然后一路回车即可

![image-20210412190521366](http://lstatic.bingoran.com/common/img/image-20210412190521366.png)

红框是公钥私钥的位置

### 2、把公钥匙链接到目标服务器的 authorized_keys (所在位置 ~/.ssh/authorized_keys)

```
ssh-copy-id -i /root/.ssh/id_rsa.pub root@XX.XX.XX.XX -p 22
```

![image-20210419161249115](http://lstatic.bingoran.com/common/img/image-20210419161249115.png)

期间会输入一次目标服务器的登录密码

### 3、在 .gitlab-ci.yam 中添加如下配置

```yaml
# 前置脚本
before_script:
  # 加载私钥
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
```

然后再添加一个上传命令，就可以把打包后的代码上传到我们指定的服务器了

```yaml
deploy-job: # 部署结果到目标服务器
  tags:
    - test
  stage: deploy
  <<: *commonConfig
  script:
    - pwd #  输出下路径
    - scp -r ./dist root@域名（或者目标服务器的ip）:/opt/www  # 将打包好的文件上到发布项目的服务器中的。放到nginx能访问到的文件夹下
```
