### ISSUE TITLE
12、.gitlab-ci.yml 优化并备份上次构建内容

### ISSUE THREAD

**Issue by bingoran** [bingoran/Blog#12]
### .gitlab-ci.yml

```yaml
#====================常量声明==============================
# gitlab常量说明（从 gitlab 变量读取）
# SSH_PRIVATE_KEY 私钥
# SERVER_ADDR 目标服务器地址
# 本地常量声明
variables:
  # 远程服务器部署目录
  DEPLOY_SERVER_PATH_PRO: /home/app/web/demo #正式环境
  DEPLOY_SERVER_PATH_DEV: /home/app/web/demo #测试环境

#  echo "${SSH_PRIVATE_KEY_DEV}"; 
#====================缓存==============================
cache: # 缓存目录
  paths:
    - node_modules # 会监听 package.json 文件的变化更新
    - dist # 打包完成后代码存放的地方
    - sourcemap # source-map

#====================公共配置==============================
image: node:14.15.4 # 指定 node 版本
.common-config: &commonConfig
  only: # 表示仅在仓库的哪些分支上执行构建
    refs:
      # 正式环境
      - master
      - release
      - production
      - pro
      # 预发布环境 | 暂时没有配置需要手动操作
      # - pre
      # 测试环境
      - develop
      - dev
      - test   

.common-npm: &commonNpm
  before_script:
    # 定义变量 如NODE环境变量
    - echo "node 环境判断"; 
    - NODE_ENV=`if [[ ${CI_COMMIT_REF_NAME:0:3} = "dev" || ${CI_COMMIT_REF_NAME:0:4} = "test" ]]; 
               then 
                 echo "dev"; 
               else 
                 echo "pro"; 
               fi`;
    - echo "当前 node 环境 ${NODE_ENV}";
    # 安装 cnpm 加速打包过程
    - npm install cnpm -g --registry=https://registry.npm.taobao.org

.common-deploy: &commonDeploy
   before_script:
    # 定义变量 DEPLOY_SERVER_PATH
    - DEPLOY_SERVER_PATH=`if [[ ${CI_COMMIT_REF_NAME:0:3} = "dev" || ${CI_COMMIT_REF_NAME:0:4} = "test" ]]; 
                            then 
                              echo "${DEPLOY_SERVER_PATH_DEV}"; 
                            else 
                              echo "${DEPLOY_SERVER_PATH_PRO}";
                            fi`;
    - echo "服务器工作目录： ${DEPLOY_SERVER_PATH}";
    - SSH_PRIVATE_KEY=`if [[ ${CI_COMMIT_REF_NAME:0:3} = "dev" || ${CI_COMMIT_REF_NAME:0:4} = "test" ]]; 
               then 
                echo "${SSH_PRIVATE_KEY_DEV_ZUIAPP}"; 
               else 
                 echo "${SSH_PRIVATE_KEY_PRO_ZUIAPP}"; 
               fi`;
    - SERVER_ADDR=`if [[ ${CI_COMMIT_REF_NAME:0:3} = "dev" || ${CI_COMMIT_REF_NAME:0:4} = "test" ]]; 
               then 
                 echo "${SERVER_ADDR_DEV}"; 
               else 
                 echo "${SERVER_ADDR_PRO}"; 
               fi`;
    # 加载私钥
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
 
#====================部署阶段==============================
stages: # 部署阶段
  - install-and-build # 安装依赖
  # - build # 打包编译
  - deploy # 部署到目标服务器

# 阶段1：安装依赖
install-and-build-job:
  tags:
    - test
  stage: install-and-build
  <<: *commonConfig
  <<: *commonNpm
  script:
    - cnpm install
    - echo "开始构建"
    - pwd
    - if [ $NODE_ENV = "dev" ];
      then
        echo "测试环境开始构建：命令 npm run beta";
        CI= cnpm run beta;
      else
        echo "正式环境开始构建：命令 npm run build";
        CI= cnpm run build2;
      fi;
  artifacts: # 提供给 gitlab 交互界面上提供下载，构建完成后可以下载构建内容
    name: 'bundle'
    expire_in: 1 week # artifacets 的过期时间，因为这些数据都是直接保存在 Gitlab 机器上的，过于久远的资源就可以删除掉了
    paths: 
      - dist/

# 阶段2: 构建项目
# build-job:
#   tags:
#     - test
#   stage: build
#   <<: *commonConfig
#   <<: *commonNpm
#   script:
#     - echo "开始构建";
#     - if [ $NODE_ENV = "dev" ];
#       then
#         echo "测试环境开始构建：命令 npm run beta";
#         CI= cnpm run beta;
#       else
#         echo "正式环境开始构建：命令 npm run build";
#         CI= cnpm run build;
#       fi;
#   artifacts: # 提供给 gitlab 交互界面上提供下载，构建完成后可以下载构建内容
#     name: 'bundle'
#     paths: 
#       - dist/

# 阶段3：部署结果到目标服务器
deploy-job: 
  # before_script:
  #   - apt-get update -qq && apt-get install -y -qq sshpass # sshpass 安装
  tags:
    - test
  stage: deploy
  <<: *commonConfig
  <<: *commonDeploy
  script:
    # 远程部署目录备份并部署新文件
    - pwd #  输出下当前 gitlab 工作目录路径
    - echo "服务器地址： ${SERVER_ADDR}";
    - echo "服务器工作目录： ${DEPLOY_SERVER_PATH}";
    - ssh root@${SERVER_ADDR} 'bash -s' < `pwd`/backup.sh ${DEPLOY_SERVER_PATH}
    - scp -r ./dist/* root@${SERVER_ADDR}:${DEPLOY_SERVER_PATH}  # 将打包好的文件上到发布项目的服务器中的，放到nginx能访问到的文件夹下
```

### backup.sh

```bash
#!/bin/bash
echo "远程服务器登录成功"
cd $1 # $1 是部署服务器的名称
FILE_NAME=`mktemp -u pm.dev.XXXXX` # 创建临时文件
DATE=`date +"%Y-%m-%dT%H_%M_%S"`
BACKUP="backup"
tar -zcvf ${FILE_NAME}.${DATE}.tar.gz ./* --exclude="$BACKUP"
# 移动备份文件到备份文件夹
if [ ! -d "$BACKUP" ]; then
mkdir "$BACKUP"
fi
mv ${FILE_NAME}.${DATE}.tar.gz "$BACKUP"
# 删除远程服务器部署目录中除backup外所有文件
# ls|egrep -v "$BACKUP"|xargs rm -rf
# 删除指定目录和文件
rm -rf dll
rm -rf static
rm -rf assets
rm -f index.html
rm -f favic.ico
echo "远程脚本执行完成，执行目录：`pwd` 备份文件夹：`ls`"
```

### 代码提交到指定分支，查看构建情况

像这样，说明 CI/CD 的流程就已经跑通了

![image-20210419163541509](http://lstatic.bingoran.com/common/img/image-20210419163541509.png)
