### ISSUE TITLE
5、使用 docker-compose.yml 安装 gitlab 服务

### ISSUE THREAD

**Issue by bingoran** [bingoran/Blog#5]
这里 gitlab 我们不直接安装，而是在 docker-compose 里通过镜像的形式进行使用

首先，创建 docker-compose.yml 文件

```bash
cd /opt/
mkdir docker_gitlab
vim docker-compose.yml
```

## docker-compose.yml

填入 gitlab 相关的内容

```yaml
version: '3.1'
services:
  # gitlab 相关
  gitlab: 
    image: 'twang2218/gitlab-ce-zh:11.1.4' # 中文版
    container_name: 'gitlab' 
    restart: always 
    privileged: true 
    hostname: 'gitz.izhiqun.com' 
    ports: 
      - '80:80' # gitlab 网络访问映射端口
      - '443:443' 
      - '22:22' # ssh 映射端口
    environment: 
      TZ: 'Asia/Shanghai' 
      GITLAB_OMNIBUS_CONFIG: | 
        external_url 'http://gitz.izhiqun.com' 
        gitlab_rails['time_zone'] = 'Asia/Shanghai' 
        gitlab_rails['gitlab_shell_ssh_port'] = 22
     volumes: 
       - /opt/docker_gitlab/config:/etc/gitlab 
       - /opt/docker_gitlab/data:/var/opt/gitlab 
       - /opt/docker_gitlab/logs:/var/log/gitlab
```

注意，这里的 ssh 映射端口可能与 centos 里边自带安装的 ssh 默认端口冲突；

所以这里改为 22 的前提是，需要修改 centos 自带 ssh 的默认端口号为其他端口号（参考上一篇）。

如果这里使用其他端口号，则将 22 修改为其他端口号就行，另外在阿里云服务器安全组放行该端口。

另外：这里 gitlab_rails['gitlab_shell_ssh_port'] 的端口需要和 ssh 端口保持一致。

**修改了 docker-compose.yml 需要重建镜像**

```bash
docker-compose build
docker-compose up -d

# 也可以使用复合指令
docker-compose up -d --build
```

## gitlab 访问

重建镜像并启动完毕，就可以访问 gitlab 了

```
#浏览器访问
http://112.124.0.72/

#设置密码
1234567

#用户名密码登录
root
1234567
```

如果 80 端口访问不了，需要在阿里云后台设置网络入方向安全组，添加80端口

![image-20210419145542037](http://lstatic.bingoran.com/common/img/image-20210419145542037.png)

### 这里补充一下 docker 中使用 gitlab 相关的命令

了解即可，后面才能用上

```bash
# step 1
docker exec -it gitlab bash
# step 2 gitlab 重载配置
gitlab-ctl reconfigure
# step 3 gitlab 重启
gitlab-ctl restart
```
