### ISSUE TITLE
9、gitlab-runner 安装

### ISSUE THREAD

**Issue by bingoran** [bingoran/Blog#9]
Runner 可以理解为：**在特定机器上**根据项目的 **.gitlab-ci.yml** 文件，对项目执行 pipeline 的**程序**。Runner 可以分为两种： **Specific Runner** 和 **Shared Runner**

- **Shared Runner **是 Gitlab 平台提供的免费使用的 runner 程序，它由 Google 云平台提供支持，每个开发团队有十几个。对于公共开源项目是免费使用的，如果是私人项目则有每月 2000 分钟的CI 时间上限。
- **Specific Runner **是我们自定义的，在自己选择的机器上运行的runner程序，gitlab给我们提供了一个叫 gitlab-runner 的命令行软件，只要在对应机器上下载安装这个软件，并且运行 gitlab-runner register 命令，然后输入从 gitlab-ci 交互界面获取的 token 进行注册， 就可以在自己的机器上远程运行pipeline程序了。

修改 docker-compose.yml 文件，添加 gitlab-runner 相关的内容

```yaml
version: '3.1'
services:
  # gitlab 相关
  ...
  # gitlab-runner 相关
  gitlab-runner: 
    image: gitlab/gitlab-runner 
    restart: always 
    container_name: 'gitlab-runner' 
    privileged: true 
    volumes: 
       - ./config:/etc/gitlab-runner
       - /var/run/docker.sock:/var/run/docker.sock #宿主机机的docker.sock映射到镜像里面
       - /usr/bin/docker:/bin/docker #宿主机的docker可执行映射到镜像里面 后面build的时候会用到，目的是在容器里边可以使用 docker 和 docker-compose 相关命令
      #  - /cache # 缓存目录
```

然后命令行执行

```bash
# 分配宿主机的权限给容器使用 - /var/run/docker.sock:/var/run/docker.sock
# 在宿主机启动 docker 程序后执行(这个是给 docker 权限给容器的)
sudo chown root:root /var/run/docker.sock 
# 在 /opt 目录中重新启动容器
docker-compose up -d --build 
# ⚠️注意：添加容器权限，保证容器可以使用宿主机的 docker(这个一定要在容器跑起来以后执行, 要不然后面自动构建会出现权限问题)
docker exec -it gitlab-runner usermod -aG root gitlab-runner
```

![image-20210412110445707](http://lstatic.bingoran.com/common/img/image-20210412110445707.png)

### 注册 gitlab-runner 到 gitlab

首先，获取在 Runner 设置时指定以下 URL，以及在安装过程中使用以下注册令牌；

位置是在，项目 -> 设置 -> CI/CD -> Runner 中

![image-20210419154714702](http://lstatic.bingoran.com/common/img/image-20210419154714702.png)

```bash
# 回到命令行执行
docker exec -it gitlab-runner gitlab-runner register
```

**⚠️注意：如果是前端项目建议 Enter an executor 这一步选择 docker**

然后选择一个镜像

```bash
[root@iZbp19ntc41vxf23iy8fi7Z ~]# docker exec -it gitlab-runner gitlab-runner register
Runtime platform                                    arch=amd64 os=linux pid=355 revision=54944146 version=13.10.0
Running in system-mode.                            
# 输入 Gitlab 实例的地址
Enter the GitLab instance URL (for example, https://gitlab.com/):
http://XXX.XXX.XXX/ # 上面的 URL
# 输入token
Enter the registration token:
XXXX # 上面的 token
# 输入 Runner 的描述
Enter a description for the runner:
[0c6a23ee0fea]: zq-runner-test
# 输入与 Runner 关联的标签
Enter tags for the runner (comma-separated):
test
Registering runner... succeeded                     runner=Fx95vBdE
# 输入 Ruuner 的执行者
Enter an executor: custom, docker-ssh, shell, docker-ssh+machine, kubernetes, docker, parallels, ssh, virtualbox, docker+machine:
docker
# 指定 docker 镜像
Enter the default Docker image (for example, ruby:2.6):
node:14.15.4
Runner registered successfully. Feel free to start it, but if it's running already the config should be automatically reloaded! 
```

当然 runner  执行者也可以选择其他

```bash
[root@iZbp19ntc41vxf23iy8fi7Z opt]# docker exec -it gitlab-runner gitlab-runner register
Runtime platform                                    arch=amd64 os=linux pid=29 revision=54944146 version=13.10.0
Running in system-mode.                            
# 输入 Gitlab 实例的地址
Enter the GitLab instance URL (for example, https://gitlab.com/):
http://XXX.XXX.XXX/ # 上面的 URL
# 输入token
Enter the registration token:
XXXX # 上面的 token
# 输入Runner的描述
Enter a description for the runner:
[0c6a23ee0fea]: zq-runner-test
# 输入与Runner关联的标签
Enter tags for the runner (comma-separated):
deploy
Registering runner... succeeded                     runner=Fx95vBdE
# 输入Ruuner的执行者：这里有坑，如果选择 shell 那么 runner 访问不到宿主环境的信息
# 前端项目建议选择 docker，具体看下面的一份配置
Enter an executor: custom, docker-ssh, shell, ssh, virtualbox, docker-ssh+machine, docker, parallels, docker+machine, kubernetes:
shell
Runner registered successfully. Feel free to start it, but if it's running already the config should be automatically reloaded! 
[root@iZbp19ntc41vxf23iy8fi7Z opt]# 
```

执行完上面步骤后，runner 就运行起来了，类似于下面这样

![image-20210419155353783](http://lstatic.bingoran.com/common/img/image-20210419155353783.png)
